### PR TITLE
Santiago edit

### PR DESCRIPTION
**Pull request by sxxgrc**
Should just be what I showed you today. Also has the safety check for the .bed extension for feature tracking (so gff files render correctly in this version). Please feel free to check over my changes (although I know there are a lot) and ask me any questions.

### CODE REVIEW

**Comment by sxxgrc** [comment]
Just added a small little prompt before exiting while in assembly mode. Nothing complex or technical about it, but it is very basic and simple so more functionality may be desired in the future.

**Comment by sxxgrc** [comment]
Last commit for a while. I believe I fixed the flickering of cursors that we saw earlier in the week, although to do so I had to comment out a line that was constantly resetting the cursor to the default cursor with each frame of the program which has very obvious consequences, although I do not know if in commenting it out any other functionality was affected.

Thank you.

**Comment by sxxgrc** [comment]
The shift select thing is done!! (I think) Please user test and destroy my dreams as necessary

**Comment by sxxgrc** [comment]
All of the experimental Assembly Chromosome stuff should be out of this request now.

**Comment by dudcha** [comment]
Thanks, Santiago!

**Comment by sa501428** [comment]
Will be first pulling in master into this branch, testing, and then updating. Temporarily closing this pull.

**Pull request closed without merging**
